---
- hosts: test
  become: yes
  gather_facts: True
  tasks:
    - name: 1 when kernel > 4.9 ensure tcp_bbr module will be load on boot
      lineinfile:
        path: /etc/modules-load.d/modules.conf
        line: 'tcp_bbr'
        state: present
        create: yes
      when: ansible_kernel is version_compare('4.9','>=')
    - name: 1.1 when kernel > 4.9 load kernel module tcp_bbr
      command: /sbin/modprobe tcp_bbr
      when: ansible_kernel is version_compare('4.9','>=')
    - name: 2. when kernel > 4.9 ensure bbr configure exists from /etc/sysctl.conf
      blockinfile: 
        path: /etc/sysctl.conf
        block: |
          # Enable google bbr:
          net.core.default_qdisc=fq 
          net.ipv4.tcp_congestion_control=bbr
          # Enable forwarding:
          net.ipv4.ip_forward=1
          # To remove docker info warning:
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
      when: ansible_kernel is version_compare('4.9','>=')
    - name: 2.1 when kernel > 4.9 reload current sysctl configuraiton.
      command: /sbin/sysctl -p
      when: ansible_kernel is version_compare('4.9','>=')

