---
- hosts: test
  become: yes
  gather_facts: false
  tasks:
    - name: 1. import elrepo repo key
      rpm_key:
        key:  https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
        state: present
    - name: 2. install elrepo repo
      yum:
        name:  http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
        state: present 
    - name: 3. install kernel-ml package from elrepo
      yum: 
        name:
          - kernel-ml
          - kernel-ml-devel
        enablerepo: elrepo-kernel
        state: present 
    - name: 4. update kernel boot order
      replace: 
        path: /etc/default/grub
        backup: yes
        regexp: '^GRUB_DEFAULT=saved$' 
        replace: 'GRUB_DEFAULT=0'
      register: replace_result
    - name: 4.1 rebuild grub after kernel boot order change
      command: /sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
      when: replace_result.changed

